// src/Account/Login.jsx
import React from 'react'
import FaFacebook from 'react-icons/lib/fa/facebook'

export class AccountLogin extends React.Component {
  render () {
    return (
      <div className='container text-center'>
        <header>
          <img src='/img/logo-square.png' alt='Mob Your Life' />
          <h1>Login</h1>
        </header>
        <p>Clique no botão abaixo para entrar com a sua conta do Facebook.</p>
        <div className='login-container'>
          <a className='btn btn-social btn-lg btn-facebook'>
            <FaFacebook />
            Entrar com Facebook
          </a>
        </div>
      </div>
    )
  }
}

// src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  templateUrl: './login.component.html'
})
export class LoginComponent {
  facebookLogin() { }
}

<div class="container text-center">
  <header class="brand-container">
    <img src="/img/logo.png" alt="Mob Your Life">
  </header>
  <div>
    Clique no botão abaixo para entrar utilizando a sua conta do Facebook.
  </div>
  <div class="login-container">
    <button class="btn btn-lg btn-social btn-facebook" (click)="facebookLogin()">
      <span class="ico-facebook">f</span>
      Entrar com Facebook
    </button>
  </div>
</div>
